version: '3.1'

services:

  dind:
    image: docker
    container_name: dind
    privileged: true
    restart: always
    environment:
      - DOCKER_TLS_CERTDIR=""
    networks:
      - dind-network

  app:
    container_name: app
    image: app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DOCKER_HOST: /var/run/docker.sock #tcp://dind:2376
    stop_signal: SIGKILL
    stdin_open: true
    tty: true
    working_dir: $PWD
    networks:
      - dind-network
      - default
    volumes:
      - $PWD:$PWD
      - $HOME/.m2:/repository
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - dind

networks:
  dind-network:
    driver: bridge
